In [15]:
import numpy as np

# Q1: Creating a 1D array and performing basic operations
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

Original Array: [1 2 3 4 5]


In [16]:
# a) Addition of 2 to all elements
arr_add = arr + 2
print("After adding 2:", arr_add)

After adding 2: [3 4 5 6 7]


In [17]:
# b) Multiply all elements by 3
arr_mul = arr * 3
print("After multiplying by 3:", arr_mul)

After multiplying by 3: [ 3  6  9 12 15]


In [18]:
# c) Divide all elements by 2
arr_div = arr / 2
print("After dividing by 2:", arr_div)

After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [19]:
# Q2: Basic NumPy Array Operations
arr = np.array([1, 2, 3, 6, 4, 5])

In [20]:
# a) Reverse the array
arr_reversed = arr[::-1]
print("Reversed Array:", arr_reversed)

Reversed Array: [5 4 6 3 2 1]


In [21]:
# b) Most frequent value and their indices
def most_frequent(arr):
    vals, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_val = vals[counts == max_count][0]
    indices = np.where(arr == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

x_most_freq, x_indices = most_frequent(x)
y_most_freq, y_indices = most_frequent(y)

print(f"Most frequent value in x: {x_most_freq}, Indices: {x_indices}")
print(f"Most frequent value in y: {y_most_freq}, Indices: {y_indices}")

Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [22]:
# Q3: Accessing elements from 2D array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at 1st row, 2nd column:", arr_2d[0, 1])
print("Element at 3rd row, 1st column:", arr_2d[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [9]:
# Q4: Creating 1D array with linspace and reshaping
my_array = np.linspace(10, 100, 25)
print("Dimensions:", my_array.ndim)
print("Shape:", my_array.shape)
print("Total Elements:", my_array.size)
print("Data Type:", my_array.dtype)
print("Total Bytes:", my_array.nbytes)


Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200


In [10]:
# Transposing using reshape
my_array_transpose = my_array.reshape(25, 1)
print("Transposed using reshape:", my_array_transpose)

Transposed using reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [11]:
# Checking T attribute
print("Transposed using T attribute:", my_array.T)  # For 1D arrays, T has no effect


Transposed using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
# Q5: Creating a 2D array and performing operations
ucs420_name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_name))
print("Median:", np.median(ucs420_name))
print("Max:", np.max(ucs420_name))
print("Min:", np.min(ucs420_name))
print("Unique Elements:", np.unique(ucs420_name))


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]


In [13]:
# Reshaping to 4x3
reshaped_ucs420_name = ucs420_name.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_ucs420_name)


Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [14]:
# Resizing to 2x3
resized_ucs420_name = np.resize(ucs420_name, (2, 3))
print("Resized to 2x3:\n", resized_ucs420_name)

Resized to 2x3:
 [[10 20 30]
 [40 50 60]]
